//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package fr.expdev.kittenmash;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.ImageView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import fr.expdev.kittenmash.R.id;
import fr.expdev.kittenmash.R.layout;

public final class BestKittenActivity_
    extends BestKittenActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_best_kitten);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
    }

    private void afterSetContentView_() {
        best_kitten = ((ImageView) findViewById(id.best_kitten));
        {
            View view = findViewById(id.fight_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BestKittenActivity_.this.fight_button();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static BestKittenActivity_.IntentBuilder_ intent(Context context) {
        return new BestKittenActivity_.IntentBuilder_(context);
    }

    @Override
    public void setBestKitten(final int kitten) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    BestKittenActivity_.super.setBestKitten(kitten);
                } catch (RuntimeException e) {
                    Log.e("BestKittenActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void saveBestKitten(final int kitten) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    BestKittenActivity_.super.saveBestKitten(kitten);
                } catch (RuntimeException e) {
                    Log.e("BestKittenActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void loadBestKitten() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    BestKittenActivity_.super.loadBestKitten();
                } catch (RuntimeException e) {
                    Log.e("BestKittenActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        BestKittenActivity_.super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  1 :
                BestKittenActivity_.this.onResult(resultCode, data);
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, BestKittenActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public BestKittenActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
